[project]
name = "kp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=1.1.2",
    "pandas>=2.3.3",
    "streamlit>=1.55.0",
]

[project.scripts]
kp = "kp:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "vps/server",
    "vps/posta",
    "services",
    "benchmarking/vpsb/postab",
    "retail/rpoc",
    "retail/mt",
    "lv",
]
